### PR TITLE
chore: upgrade go; for: #2

### PR DESCRIPTION
**Pull request by Nasfame**
- For #2 : brought down go.sum from 700+ to 26 lines

- Upgrade go to go1.21

### CODE REVIEW

**Comment by bioball** [comment]
Thank you! Some tests are failing:

```
Running Pkl snippet tests
go: errors parsing go.mod:
/home/circleci/project/go.mod:5: unknown directive: toolchain
```

The issue is that we're using the golang.org/x/mod package to parse a `go.mod` file. But, the only reason we do that is so we can determine the module name.

It looks like the latest release (v0.15.0) doesn't understand the `toolchain` directive in a go.mod file.

We can probably replace that logic [here](https://github.com/apple/pkl-go/blob/main/cmd/pkl-gen-go/pkg/generate.go#L56) with a simple regex.

You can run the same tests locally via `./scripts/test_snippets.sh`.

**Comment by Nasfame** [comment]
@bioball I have upgraded the go version to go 1.21. That's probably why

**Comment by Nasfame** [comment]
Done. I think bug is fixed now.

**Comment by Nasfame** [comment]
@bioball Its not x/mod 's problem, its the go standard lib issue. I have updated the base images to go1.21. 

Thanks for sharing the script, Its working fine for me

```
bin/zsh -c ./scripts/test_snippets.sh
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/Classes.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
Determined base path to be github.com/apple/pkl-go from go.mod
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/bugholder/Person.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/bugholder/Bike.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/bugholder/Being.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/bugholder/D.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/bugholder/C.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/bugholder/B.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/bugholder/bugkindtwo/BugKindTwo.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/bugholder/BugHolder.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/bugholder/ThisPerson.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/bugholder/A.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/bugholder/bugkind/BugKind.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/bugholder/init.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/bugholder/Bug.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/bugholder/Wheel.pkl.go
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/ConflictingNames.err.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/ConflictingNames2.err.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/CyclicModule.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/cyclicmodule/CyclicModule.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/cyclicmodule/Cyclic.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/cyclicmodule/init.pkl.go
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/EmptyOpenModule.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/emptyopenmodule/init.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/emptyopenmodule/EmptyOpenModule.pkl.go
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/ExplicitName.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/explicitname/configtype/ConfigType.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/explicitname/ExplicitlyCoolName.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/explicitname/SomethingVeryFunny.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/explicitname/init.pkl.go
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/ExtendAbstractClass.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/extendabstractclass/ExtendsAbstractClass.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/extendabstractclass/A.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/extendabstractclass/B.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/extendabstractclass/init.pkl.go
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/ExtendModule.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/support/openmodule/init.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/extendmodule/ExtendModule.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/extendmodule/init.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/support/openmodule/MyModule.pkl.go
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/ExtendOpenClass.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/extendopenclass/MyClass2.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/extendopenclass/init.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/support/lib3/GoGoGo.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/support/lib3/Lib3.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/support/lib3/init.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/extendopenclass/ExtendingOpenClass.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/extendopenclass/MyClass.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/extendopenclass/MyOpenClass.pkl.go
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/HiddenProperties.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/hiddenproperties/HiddenProperties.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/hiddenproperties/init.pkl.go
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/IllegalOverride.err.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/InvalidPackageName.err.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/ModuleType.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/support/lib4/init.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/moduletype/ModuleType.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/moduletype/init.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/support/lib4/MyLib4.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/support/lib4/Lib4.pkl.go
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/ModuleUsingLib.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/moduleusinglib/init.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/support/lib/MyClass.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/support/lib/Lib.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/support/lib/init.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/support/lib/myenum/MyEnum.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/support/lib2/cities/Cities.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/moduleusinglib/ModuleUsingLib.pkl.go
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/Override.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/override/init.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/override/Override.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/override/Foo.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/override/Bar.pkl.go
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/Override2.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/override2/init.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/override2/Override2.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/override2/MySubclass.pkl.go
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/StructTags.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/structtags/StructTags.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/structtags/init.pkl.go
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/UnionNameKeyword.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/unionnamekeyword/_type/Type.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/unionnamekeyword/UnionNameKeyword.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/unionnamekeyword/init.pkl.go
Generating Go sources for module /Volumes/N/golangFame/pkl-go/codegen/snippet-tests/input/Unions.pkl
Using custom generator script: /Volumes/N/golangFame/pkl-go/codegen/src/Generator.pkl
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/union/init.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/union/city/City.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/union/county/County.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/union/noodles/Noodles.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/union/accountdisposition/AccountDisposition.pkl.go
/Volumes/N/golangFame/pkl-go/codegen/snippet-tests/output/union/Union.pkl.go


```

**Comment by bioball** [comment]
Ah, thanks!

**Pull request merged**
